[versions]
minecraft = "1.20.2"
fabric-loader = "0.14.24"
fabric-api = "0.90.7+1.20.2"
fabric-kotlin = "1.10.13+kotlin.1.9.20"
sheeplib = "1.1.0"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }
sheeplib = { group = "com.noxcrew.sheeplib", name = "api", version.ref = "sheeplib" }
